using LibCommon.Lib.Localization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Lib.VoiceServices.GoogleTTS
{
    public static class GoogleTTSVoiceCode
    {
        private static readonly Dictionary<string, string> LanguageMapVi = new Dictionary<string, string>
        {
            { "af-ZA", "Tiếng Afrikaans (Nam Phi)" },
            { "am-ET", "Tiếng Amharic (Ethiopia)" },
            { "ar-XA", "Tiếng Ả Rập" },
            { "bg-BG", "Tiếng Bulgaria" },
            { "bn-IN", "Tiếng Bengal (Ấn Độ)" },
            { "ca-ES", "Tiếng Catalan (Tây Ban Nha)" },
            { "cmn-CN", "Tiếng Quan Thoại (Trung Quốc)" },
            { "cmn-TW", "Tiếng Quan Thoại (Đài Loan)" },
            { "cs-CZ", "Tiếng Séc (Cộng hòa Séc)" },
            { "da-DK", "Tiếng Đan Mạch" },
            { "de-DE", "Tiếng Đức" },
            { "el-GR", "Tiếng Hy Lạp" },
            { "en-AU", "Tiếng Anh (Úc)" },
            { "en-GB", "Tiếng Anh (Anh)" },
            { "en-IN", "Tiếng Anh (Ấn Độ)" },
            { "en-US", "Tiếng Anh (Mỹ)" },
            { "es-ES", "Tiếng Tây Ban Nha (Tây Ban Nha)" },
            { "es-US", "Tiếng Tây Ban Nha (Mỹ)" },
            { "et-EE", "Tiếng Estonia" },
            { "eu-ES", "Tiếng Basque (Tây Ban Nha)" },
            { "fi-FI", "Tiếng Phần Lan" },
            { "fil-PH", "Tiếng Filipino (Philippines)" },
            { "fr-CA", "Tiếng Pháp (Canada)" },
            { "fr-FR", "Tiếng Pháp (Pháp)" },
            { "gl-ES", "Tiếng Galicia (Tây Ban Nha)" },
            { "gu-IN", "Tiếng Gujarati (Ấn Độ)" },
            { "he-IL", "Tiếng Hebrew (Israel)" },
            { "hi-IN", "Tiếng Hindi (Ấn Độ)" },
            { "hr-HR", "Tiếng Hrvatska (Cộng hòa Croatia)" },
            { "hu-HU", "Tiếng Hungary" },
            { "id-ID", "Tiếng Indonesia" },
            { "is-IS", "Tiếng Iceland" },
            { "it-IT", "Tiếng Ý" },
            { "ja-JP", "Tiếng Nhật" },
            { "kn-IN", "Tiếng Kannada (Ấn Độ)" },
            { "ko-KR", "Tiếng Hàn Quốc" },
            { "lt-LT", "Tiếng Lithuania" },
            { "lv-LV", "Tiếng Latvia" },
            { "ml-IN", "Tiếng Malayalam (Ấn Độ)" },
            { "mr-IN", "Tiếng Marathi (Ấn Độ)" },
            { "ms-MY", "Tiếng Malaysia" },
            { "nb-NO", "Tiếng Na Uy (Bokmål)" },
            { "nl-BE", "Tiếng Hà Lan (Bỉ)" },
            { "nl-NL", "Tiếng Hà Lan (Hà Lan)" },
            { "pa-IN", "Tiếng Punjabi (Ấn Độ)" },
            { "pl-PL", "Tiếng Ba Lan" },
            { "pt-BR", "Tiếng Bồ Đào Nha (Brazil)" },
            { "pt-PT", "Tiếng Bồ Đào Nha (Bồ Đào Nha)" },
            { "ro-RO", "Tiếng Romania" },
            { "ru-RU", "Tiếng Nga" },
            { "sk-SK", "Tiếng Slovakia" },
            { "sl-SI", "Tiếng Slovenia (Slovene)" },
            { "sr-RS", "Tiếng Serbia" },
            { "sv-SE", "Tiếng Thụy Điển" },
            { "sw-KE", "Tiếng Swahili (Kiswahili)" },
            { "ta-IN", "Tiếng Tamil (Ấn Độ)" },
            { "te-IN", "Tiếng Telugu (Ấn Độ)" },
            { "th-TH", "Tiếng Thái Lan" },
            { "tr-TR", "Tiếng Thổ Nhĩ Kỳ" },
            { "uk-UA", "Tiếng Ukraina" },
            { "ur-IN", "Tiếng Urdu (Ấn Độ)" },
            { "vi-VN", "Tiếng Việt" },
            { "yue-HK", "Tiếng Quảng Đông (Hồng Kông)" }
        };

        private static readonly Dictionary<string, string> LanguageMapEn = new Dictionary<string, string>
        {
            { "af-ZA", "Afrikaans (South Africa)" },
            { "am-ET", "Amharic (Ethiopia)" },
            { "ar-XA", "Arabic" },
            { "bg-BG", "Bulgarian" },
            { "bn-IN", "Bengali (India)" },
            { "ca-ES", "Catalan (Spain)" },
            { "cmn-CN", "Mandarin Chinese (China)" },
            { "cmn-TW", "Mandarin Chinese (Taiwan)" },
            { "cs-CZ", "Czech (Czech Republic)" },
            { "da-DK", "Danish" },
            { "de-DE", "German" },
            { "el-GR", "Greek" },
            { "en-AU", "English (Australia)" },
            { "en-GB", "English (UK)" },
            { "en-IN", "English (India)" },
            { "en-US", "English (US)" },
            { "es-ES", "Spanish (Spain)" },
            { "es-US", "Spanish (US)" },
            { "et-EE", "Estonian" },
            { "eu-ES", "Basque (Spain)" },
            { "fi-FI", "Finnish" },
            { "fil-PH", "Filipino (Philippines)" },
            { "fr-CA", "French (Canada)" },
            { "fr-FR", "French (France)" },
            { "gl-ES", "Galician (Spain)" },
            { "gu-IN", "Gujarati (India)" },
            { "he-IL", "Hebrew (Israel)" },
            { "hi-IN", "Hindi (India)" },
            { "hr-HR", "Croatian (Croatia)" },
            { "hu-HU", "Hungarian" },
            { "id-ID", "Indonesian" },
            { "is-IS", "Icelandic" },
            { "it-IT", "Italian" },
            { "ja-JP", "Japanese" },
            { "kn-IN", "Kannada (India)" },
            { "ko-KR", "Korean" },
            { "lt-LT", "Lithuanian" },
            { "lv-LV", "Latvian" },
            { "ml-IN", "Malayalam (India)" },
            { "mr-IN", "Marathi (India)" },
            { "ms-MY", "Malay" },
            { "nb-NO", "Norwegian (Bokmål)" },
            { "nl-BE", "Dutch (Belgium)" },
            { "nl-NL", "Dutch (Netherlands)" },
            { "pa-IN", "Punjabi (India)" },
            { "pl-PL", "Polish" },
            { "pt-BR", "Portuguese (Brazil)" },
            { "pt-PT", "Portuguese (Portugal)" },
            { "ro-RO", "Romanian" },
            { "ru-RU", "Russian" },
            { "sk-SK", "Slovak" },
            { "sl-SI", "Slovenian" },
            { "sr-RS", "Serbian" },
            { "sv-SE", "Swedish" },
            { "sw-KE", "Swahili" },
            { "ta-IN", "Tamil (India)" },
            { "te-IN", "Telugu (India)" },
            { "th-TH", "Thai" },
            { "tr-TR", "Turkish" },
            { "uk-UA", "Ukrainian" },
            { "ur-IN", "Urdu (India)" },
            { "vi-VN", "Vietnamese" },
            { "yue-HK", "Cantonese (Hong Kong)" }
        };

        public static string GetLanguageDisplayName(string languageCode)
        {
            var map = LibLocalizer.IsEnglish ? LanguageMapEn : LanguageMapVi;
            return map.TryGetValue(languageCode, out var name) ? name : languageCode;
        }
    }
}
